[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
calculator = "64mU9SLvqv8texzRsRMKgG13kRXx1QkXPHAJ9jBVhDUL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
